# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a79586fb-a702-45aa-9ec1-090fb704d266";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/664E-9763";
      fsType = "vfat";
    };

  fileSystems."/home/jacob/Mounts/Storage1" =
    { device = "/dev/disk/by-uuid/71a3b269-6f3e-4ff9-8111-8a32e386ccc3";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2ce76b04-b27c-4caf-9361-b81a3927d7f1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-496e67060a0e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-abca868523c4.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-ae480b113650.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-e9a7acc0f1de.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-eb45f8d0cef8.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth26f3d5f.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethefb4525.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
